# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BTA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='office',
            new_name='office_adress',
        ),
    ]
