# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTA', '0003_auto_20170607_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='person',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
