# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTA', '0004_meeting_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='office_adress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='person',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='finish_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
