# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTA', '0005_auto_20170608_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='comfort',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
