# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTA', '0007_trip_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hotel_price',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_stars',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
