# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTA', '0008_auto_20170609_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departure_at',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight_price',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='return_at',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
